version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  redis:
    image: redis
    ports:
      - "6378:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_api
    command: sh -c "./setup.sh"
    volumes:
      - .:/code
    ports:
      - 8080:8000
    environment:
      DBHOST: db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    restart: no
  
volumes:
  postgres_data: